name: Pack and Publish OCI Image to Docker Registry

on:
  schedule:
    # Daily for now
    - cron: "9 7 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-rock:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pack with Rockcraft
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - name: Upload Rock Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cups-rock
          path: ${{ steps.rockcraft.outputs.rock }}

  publish-rock:
    needs: build-rock
    if: github.ref_name == 'main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Rock Artifact
        uses: actions/download-artifact@v4
        with:
          name: cups-rock

      - name: Install Dependencies
        run: |
          sudo snap install rockcraft --classic --channel=edge
          sudo snap install yq

      - name: Build and Push Docker Image
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          ls
          IMAGE="$(yq '.name' rockcraft.yaml)"
          VERSION="$(yq '.version' rockcraft.yaml)"
          ROCK="$(ls *.rock | tail -n 1)"
          sudo skopeo --insecure-policy copy oci-archive:"${ROCK}" docker-daemon:"${USERNAME}/${IMAGE}:${VERSION}"
          docker push ${USERNAME}/${IMAGE}:${VERSION}
